version: '3'

services:
  service_scaffold:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./env/local.env
    volumes:
      - './env/local.config.yaml:/config.yaml'
    ports:
    - '8090:8090'
    networks:
      scaffold:

  postgres:
    image: postgres:12-alpine
    env_file:
      - ./env/local.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      scaffold:

volumes:
  postgres_data: {}

networks:
  scaffold: {}
