#Example of delete request
DELETE http://localhost:2490/dev/test/buzz/10
Accept: */*
Content-Type: application/json
Jwt: {"jti":"1"}

###

DELETE http://localhost:2490/dev/couch/3
Accept: */*
Content-Type: application/json
Jwt: {"jti":"1"}

###