#Verify generated enum type

POST http://localhost:2490/dev/test/buzz
Accept: */*
Content-Type: application/json
Jwt: {"jti":"1"}

{"name": "test","buzzType": "testA","description": "test object"}

###