# get the list of obj
GET http://localhost:2490/dev/buzz?param=test
Accept: */*
Content-Type: application/json
Jwt: {"jti":"1"}
###
# get the list of obj from the end
GET http://localhost:2490/dev/buzz?order=desc&param=test
Accept: */*
Content-Type: application/json
Jwt: {"jti":"1"}
###
# get the first 10 obj
GET http://localhost:2490/dev/buzz?pageSize=10&param=test
Accept: */*
Content-Type: application/json
Jwt: {"jti":"1"}
###
# get 10 obj on second page
GET http://localhost:2490/dev/buzz?pageSize=10&page=2&param=test
Accept: */*
Content-Type: application/json
Jwt: {"jti":"1"}
###