dev_mode: true
check_auth: false
services_init_timeout: 15 # in seconds

api:
  host: localhost
  port: 2490
  dev_mode: true
  enable_cors: true
  api_request_timeout: 60

db:
  conn_url: "postgres://user:password@localhost/skeleton_db?sslmode=disable"
  init_timeout: 60 # in seconds
  auto_migrate: true
  wait_for_db: true

# optional parameter -> connection string to couchDB
#couchdb: "http://127.0.0.1:5984/"

log:
  app_name: service-scaffold
  level: debug
  add_trace: true
  sentry: ""
  json: false

nats:
  host: 127.0.0.1
  port: 4222

workers:
  - api-server
  - foobar
