// Code generated by forge bindata.
// sources:
// pg/001_base.sql
// pg/002_add_buzz_type.sql
// DO NOT EDIT!

package schema

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _pg001_baseSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x6c\xcf\xcb\x4a\xc3\x40\x14\xc6\xf1\xfd\x79\x8a\x6f\x97\x16\xed\x46\xe8\xaa\xab\x69\x73\x8a\xa3\xe3\x24\xce\x45\x92\x95\x44\x33\xca\x80\xb9\x90\x44\x84\x88\xef\x2e\x46\xbc\x80\x9e\xf5\x8f\xf3\xf1\xdf\x6c\x70\xd2\xc4\xc7\xa1\x9a\x02\x7c\x4f\x07\xc3\xc2\x31\x9c\xd8\x2b\x86\x3c\x42\x67\x0e\x5c\x48\xeb\x2c\xee\x9e\xe7\xf9\xf6\x21\x84\x7a\xc4\x8a\x80\x58\xe3\xfb\x2c\x1b\x29\x14\x72\x23\xaf\x84\x29\x71\xc9\xe5\x29\x01\x6d\xd5\x84\x2f\x71\x23\xcc\xe1\x5c\x98\xd5\xd9\x76\xbb\x86\xd7\xf2\xda\xf3\x07\xa9\xc3\x78\x3f\xc4\x7e\x8a\x5d\x0b\xc7\x85\xc3\x32\xa8\xbd\x52\x48\xf9\x28\xbc\x72\x48\x92\x4f\x38\x55\xf1\x69\x5c\x7e\x5d\xd8\x4c\xef\xff\x81\xaf\x6f\x09\xad\x77\x44\x44\xbf\xa3\xd2\xee\xa5\xa5\xd4\x64\xf9\x4f\xd4\x9f\xa0\x1d\xbd\x07\x00\x00\xff\xff\xbb\x51\xe7\x27\x07\x01\x00\x00")

func pg001_baseSqlBytes() ([]byte, error) {
	return bindataRead(
		_pg001_baseSql,
		"pg/001_base.sql",
	)
}

func pg001_baseSql() (*asset, error) {
	bytes, err := pg001_baseSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "pg/001_base.sql", size: 263, mode: os.FileMode(420), modTime: time.Unix(1574112585, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _pg002_add_buzz_typeSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x94\x91\xcf\x8a\x83\x30\x18\xc4\xef\x79\x8a\xb9\xb9\xcb\xae\x4f\xe0\x29\x9a\x2c\x08\xfe\x43\x23\x6c\x4f\x62\xeb\x57\xf1\x50\x2b\x1a\x29\xf5\xe9\x4b\x2d\xd6\x96\x56\xb0\xb7\x61\xc8\x6f\x26\xc3\x67\x9a\xf8\x39\x54\x65\x9b\x6b\x42\xda\x30\x27\x96\x5c\x49\xa8\x4d\x24\xa1\xa9\xd3\x99\x3e\x37\x04\x9e\x40\x06\xa9\x8f\x2f\xe3\xea\x71\xe3\x17\xa3\xb0\x27\xe1\x4c\x42\x18\xdf\x16\xe3\x9e\x92\x31\x14\xb7\x3d\x89\x6d\x3f\x0c\xd9\x9e\xa8\xe8\xc0\x85\x80\x13\x7a\xa9\x1f\xdc\xdc\x31\xf9\xde\xb1\x06\xdb\xb5\x94\x6b\x2a\xb2\x5c\xa3\xaa\x35\x95\xd4\xae\xa1\xfa\xa6\x78\xa1\xd8\xe3\x6c\x71\x3c\xd5\x4b\x39\x22\x0e\xa3\x29\xc8\xfd\x83\xfc\x77\x13\x95\xcc\xff\x5f\xec\x7f\xcf\xcd\x03\x3e\x04\xe7\x0d\x16\x1b\x5f\x3c\x1f\xc8\xba\x04\x00\x00\xff\xff\xa0\x5e\x57\x5d\xc6\x01\x00\x00")

func pg002_add_buzz_typeSqlBytes() ([]byte, error) {
	return bindataRead(
		_pg002_add_buzz_typeSql,
		"pg/002_add_buzz_type.sql",
	)
}

func pg002_add_buzz_typeSql() (*asset, error) {
	bytes, err := pg002_add_buzz_typeSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "pg/002_add_buzz_type.sql", size: 454, mode: os.FileMode(420), modTime: time.Unix(1556966131, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"pg/001_base.sql":          pg001_baseSql,
	"pg/002_add_buzz_type.sql": pg002_add_buzz_typeSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"pg": &bintree{nil, map[string]*bintree{
		"001_base.sql":          &bintree{pg001_baseSql, map[string]*bintree{}},
		"002_add_buzz_type.sql": &bintree{pg002_add_buzz_typeSql, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
